version: '3'

services:
  homepage:
    container_name: homepage
    image: lamprojects-homepage
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: always